### ISSUE TITLE
Duplicate versions in which versions are supported

### ISSUE THREAD

**Issue by nmerket** [NREL/hpxml_version_translator#65]
![image](https://user-images.githubusercontent.com/5325034/148270673-7fc3e899-e9b3-45c9-ab84-d66a4fbe66ca.png)

cc @shorowit

**Comment by shorowit** [comment]
Oops, they aren't duplicate. I think I misread the 2.2.1 version because I wasn't expecting minor versions to be included here too. So, not an issue.
